:toc: macro
:toclevels: 5
:figure-caption!:

:milestoner_link: link:https://alchemists.io/projects/milestoner[Milestoner]

= Docker Alpine Base

Provides a base link:https://www.alpinelinux.org[Alpine Linux] Docker image with a minimal set of
tooling. Great for being used as a foundational image for building on top of, for example, the
link:https://alchemists.io/projects/docker-alpine-ruby[Docker Alpine Ruby] image.

toc::[]

== Features

* Installs CA Certificates.
* Installs link:https://www.gnu.org/software/bash[Bash].
* Installs link:https://curl.se[Curl].
* Installs link:https://gnupg.org[GnuPG].
* Installs and configures link:https://git-scm.com[Git] (including default branch).
* Installs link:https://www.openssl.org[OpenSSL].
* Installs link:https://www.openssh.com[OpenSSH].
* Installs and configures link:https://www.vim.org[Vim] as default editor.
* Sets link:https://en.wikipedia.org/wiki/Xterm[xterm] as default terminal.

== Requirements

. link:https://www.docker.com[Docker].

== Setup

To set up the project, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/docker-alpine-base.git
cd docker-alpine-base
git checkout 3.16.0
----

== Usage

All versions of this image can be found on
link:https://hub.docker.com/r/bkuhlmann/alpine-base/tags[Docker Hub]. The image can be pulled as follows:

[source,bash]
----
docker pull bkuhlmann/alpine-base:latest  # Pull latest version.
docker pull bkuhlmann/alpine-base:3.16.0  # Pull specific version.
----

You can also build on top of this image via your `Dockerfile`:

[source,dockerfile]
----
FROM bkuhlmann/alpine-base:latest  # Latest version.
FROM bkuhlmann/alpine-base:3.16.0  # Specific version.
----

== Development

To contribute, run:

[source,bash]
----
git clone https://github.com/bkuhlmann/docker-alpine-base.git
cd docker-alpine-base
----

To build, run:

[source,bash]
----
bin/build
----

To use the console, run:

[source,bash]
----
bin/console
----

To deploy the _latest_ version, run:

[source,bash]
----
bin/deploy
----

To automatically calculate the next logical version and deploy it, run:

[source,bash]
----
bin/deploy p
----

Versions are calculated and created via the {milestoner_link} gem. Best practice is to deploy both the latest version and next version. Example:

[source,bash]
----
bin/deploy
bin/deploy p
----

The above will ensure new images are created with the following tags:

* `latest`: This is the most recent stable version which may or may not be ahead of the last version released.
* `<major>.<minor>.<patch>`: This the next logical version as calculated and created by {milestoner_link}.

== Tests

To test, run:

[source,bash]
----
bin/console
bash --version
curl --version
git --version
gpg --version
openssl version
ssh -V
vim --version
----

== link:https://alchemists.io/policies/license[License]

== link:https://alchemists.io/policies/security[Security]

== link:https://alchemists.io/policies/code_of_conduct[Code of Conduct]

== link:https://alchemists.io/policies/contributions[Contributions]

== link:https://alchemists.io/policies/developer_certificate_of_origin[Developer Certificate of Origin]

== link:https://alchemists.io/projects/docker-alpine-base/versions[Versions]

== link:https://alchemists.io/community[Community]

== Credits

* Built with link:https://alchemists.io/projects/rubysmith[Rubysmith].
* Engineered by link:https://alchemists.io/team/brooke_kuhlmann[Brooke Kuhlmann].
